apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  autoAssign: true
  avoidBuggyIPs: false
  addresses:
    - 192.168.1.100/32 # Cluster VIP
