apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app/
  - config/metallb/
  - config/kube-system/ # Cilium Gateway API
  - config/gateway-infra/
  - config/demo-app/
  - config/cert-manager/
  - config/kyverno/
  - config/argocd/
