apiVersion: v1
kind: Secret
metadata:
  name: gitlab-oidc-secret
  namespace: gateway-infra
type: Opaque
stringData:
  client-secret: "gloas-2ff379584aac7ccbfb53050f00c4d8ff56276f764eb13b8a9e54867270c2a524"
