apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: require-oidc-and-authz
  namespace: demo-app
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: http-app-route

  oidc:
    provider:
      issuer: "https://auth.192.168.1.100.sslip.io/realms/kube-lab"
      authorizationEndpoint: "https://auth.192.168.1.100.sslip.io/realms/kube-lab/protocol/openid-connect/auth"
      tokenEndpoint: "https://auth.192.168.1.100.sslip.io/realms/kube-lab/protocol/openid-connect/token"
      backendRefs:
        - group: ""
          kind: Service
          name: keycloakx-http
          namespace: keycloak
          port: 80

    clientID: "envoy-demo-app"
    clientSecret:
      name: envoy-demo-app-secret
    redirectURL: "https://demo.192.168.1.100.sslip.io/oauth2/callback"
    logoutPath: "/logout"
    scopes:
      - openid
      - email
      - profile
      - groups
    cookieNames:
      accessToken: "keycloak-access-token"

  jwt:
    providers:
      - name: keycloak-jwt-provider
        issuer: "https://auth.192.168.1.100.sslip.io/realms/kube-lab"
        remoteJWKS:
          uri: "http://keycloakx-http.keycloak.svc.cluster.local/realms/kube-lab/protocol/openid-connect/certs"
        extractFrom:
          cookies:
            - "keycloak-access-token"

  # authorization:
  #   defaultAction: Deny
  #   rules:
  #     - name: "allow-dev-and-sre"
  #       action: Allow
  #       principal:
  #         jwt:
  #           provider: keycloak-jwt-provider
  #           claims:
  #             - name: groups
  #               valueType: StringArray
  #               values:
  #                 # - "developer"
  #                 - "sre"
