apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
type: Opaque
stringData:
  password: keycloak
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-password
  namespace: keycloak
type: Opaque
stringData:
  password: "admin"
