apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sslip-io-cert
  namespace: gateway-infra
spec:
  isCA: false
  commonName: "*.192.168.1.100.sslip.io"
  dnsNames:
    - "*.192.168.1.100.sslip.io"
  secretName: sslip.io-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
