apiVersion: cilium.io/v2
kind: CiliumClusterwideEnvoyConfig
metadata:
  name: envoy-oauth2-clusterwide
spec:
  backendServices:
    - name: keycloakx-http
      namespace: keycloak
      number:
        - "80"

  resources:
    - "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret
      name: oauth_token_secret
      generic_secret:
        secret:
          inline_bytes: "fixme"

    - "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret
      name: oauth_hmac_secret
      generic_secret:
        secret:
          inline_bytes: "fixme"

    - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
      name: cilium-gateway-gateway-infra-shared-gateway
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http

                rds:
                  config_source:
                    ads: {}
                    resource_api_version: V3
                  route_config_name: cilium-gateway-gateway-infra-shared-gateway

                http_filters:
                  - name: envoy.filters.http.oauth2
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.oauth2.v3.OAuth2
                      config:
                        token_endpoint:
                          cluster: "gateway-infra/cilium-gateway-shared-gateway/keycloak:keycloakx-http:80"
                          uri: https://auth.192.168.1.100.sslip.io/realms/kube-lab/protocol/openid-connect/token
                          timeout: 5s
                        authorization_endpoint: https://auth.192.168.1.100.sslip.io/realms/kube-lab/protocol/openid-connect/auth
                        redirect_uri: "%REQ(:scheme)%://%REQ(:authority)%/oauth2/callback"
                        redirect_path_matcher:
                          path:
                            exact: /oauth2/callback
                        signout_path:
                          path:
                            exact: /logout
                        forward_bearer_token: true

                        pass_through_matcher:
                          - name: ":authority"
                            string_match:
                              exact: "auth.192.168.1.100.sslip.io"

                        credentials:
                          client_id: "envoy-demo-app"
                          token_secret:
                            name: oauth_token_secret
                            sds_config:
                              ads: {}
                              resource_api_version: V3
                          hmac_secret:
                            name: oauth_hmac_secret
                            sds_config:
                              ads: {}
                              resource_api_version: V3

                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
