apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gateway-infra

resources:
  - github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=v1.5.0
  - namespace.yaml
  - gateway.yaml
  - certificate.yaml
  - clusterwideconfig.yaml
  - secrets.yaml

# Inject Envoy Generic Secret from Kubernetes Secret
replacements:
  - source:
      kind: Secret
      name: oauth-proxy-credentials
      fieldPath: data.token-secret
    targets:
      - select:
          kind: CiliumClusterwideEnvoyConfig
          name: envoy-oauth2-clusterwide
        fieldPaths:
          - spec.resources.[name=oauth_token_secret].generic_secret.secret.inline_bytes

  - source:
      kind: Secret
      name: oauth-proxy-credentials
      fieldPath: data.hmac-secret
    targets:
      - select:
          kind: CiliumClusterwideEnvoyConfig
          name: envoy-oauth2-clusterwide
        fieldPaths:
          - spec.resources.[name=oauth_hmac_secret].generic_secret.secret.inline_bytes
