apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gateway-infra

resources:
  - namespace.yaml
  - gateway.yaml
  - certificate.yaml
  - secrets.yaml
  - gitlab-secret.yaml
  - reference-grant-gitlab.yaml
