apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gateway-infra

resources:
  - github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=v1.5.0
  - namespace.yaml
  - gateway.yaml
  - certificate.yaml
  - secrets.yaml
  - oauth2-http-route.yaml
  - auth-policy.yaml
  - envoy-filter-403.yaml

helmCharts:
  - name: oauth2-proxy
    repo: https://oauth2-proxy.github.io/manifests
    version: "10.1.4"
    releaseName: oauth2-proxy
    namespace: gateway-infra
    valuesFile: oauth2-proxy-values.yaml
