apiVersion: v1
kind: Secret
metadata:
  name: oauth-proxy-credentials
  namespace: gateway-infra
type: Opaque
data:
  # Retrived using: terraform output -raw demo_app_client_secret | base64
  token-secret: "WkxoVnRBZ0VpS0hRWFNqYUJUbUNPOG9XQVhQSzRTVU8="

  # Retrived using: head -c 32 /dev/urandom | base64
  hmac-secret: "OEf2atYd3Z/RsbWWqfUSR6osr3NJdu5hRsvMH9R/YYc="
