apiVersion: v1
kind: Secret
metadata:
  name: oauth-proxy-credentials
  namespace: gateway-infra
type: Opaque
stringData:
  client-id: "envoy-demo-app"
  # Retrived using: terraform output -raw demo_app_client_secret
  client-secret: "KgDVDbXacdGZyf6VDkeIHVDNxMvXAcx6"
  cookie-secret: "8xfRAXj/V+i8UOPV5HBo9lmnn2RqOt7O"
